
import React, { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState, setManualMatches, addManualMatch, updateManualMatch, removeManualMatch, addLog } from '../store';
import { ManualMatch, Status } from '../types';
import { Icons, getStatusStyles } from '../constants';
import { apiService } from '../services/apiService';
import { socketService } from '../services/socketService';
import { useEffect } from 'react';

const ManualMatching: React.FC = () => {
  const { manualMatches, user } = useSelector((state: RootState) => state.admin);
  const dispatch = useDispatch();

  const fetchMatches = async () => {
    const matches = await apiService.getManualMatches();
    dispatch(setManualMatches(matches));
  };

  useEffect(() => {
    fetchMatches();

    // Real-time updates
    const socket = socketService.connect();
    socket.on('data_updated', (payload) => {
      if (payload.module === 'manualMatches') {
        fetchMatches();
      }
    });

    return () => {
      // socket.off('data_updated');
    };
  }, [dispatch]);

  const [showAddModal, setShowAddModal] = useState(false);
  const [editingMatch, setEditingMatch] = useState<ManualMatch | null>(null);
  const [formData, setFormData] = useState<Partial<ManualMatch>>({
    status: Status.TRIAL_PENDING
  });

  const handleAddSubmit = async () => {
    if (!formData.parentName || !formData.phoneNumber) {
      alert("Please enter parent name and contact number.");
      return;
    }
    const entry: any = { // ID generated by backend
      parentName: formData.parentName!,
      phoneNumber: formData.phoneNumber!,
      subject: formData.subject || 'Not Specified',
      gradeLevel: formData.gradeLevel || 'Not Specified',
      status: (formData.status as Status) || Status.TRIAL_PENDING,
      dateAdded: new Date().toISOString().split('T')[0]
    };

    try {
      const newMatch = await apiService.addManualMatch(entry);
      dispatch(addManualMatch(newMatch));
      dispatch(addLog({ activity: `Created manual match record for ${newMatch.parentName}`, admin: user?.name || 'Admin', status: 'success' }));
      setShowAddModal(false);
      setFormData({ status: Status.TRIAL_PENDING });
    } catch (error) {
      alert("Failed to create match");
    }
  };

  const handleEditSubmit = async () => {
    if (editingMatch) {
      try {
        await apiService.updateManualMatch(editingMatch);
        dispatch(updateManualMatch(editingMatch));
        dispatch(addLog({ activity: `Modified match record for ${editingMatch.parentName}`, admin: user?.name || 'Admin', status: 'info' }));
        setEditingMatch(null);
      } catch (error) {
        alert("Failed to update match");
      }
    }
  };

  const handleDelete = async (id: string, name: string) => {
    if (window.confirm(`Permanently remove match record for ${name}?`)) {
      try {
        await apiService.deleteManualMatch(id);
        dispatch(removeManualMatch(id));
        dispatch(addLog({ activity: `Deleted match record: ${name}`, admin: user?.name || 'Admin', status: 'warning' }));
      } catch (error) {
        alert("Failed to delete match");
      }
    }
  };

  return (
    <div className="p-4 lg:p-8 animate-saas max-w-7xl mx-auto pb-24">
      <div className="ds-card">
        <div className="px-6 lg:px-8 py-5 lg:py-6 border-b border-[var(--border-ds)] flex items-center justify-between gap-4">
          <div className="overflow-hidden">
            <h2 className="text-base font-bold text-[var(--text-main)] tracking-tight truncate">Match Registry</h2>
            <p className="text-xs text-[var(--text-sub)] mt-0.5 truncate hidden sm:block">Specialized trial management</p>
          </div>
          <button
            onClick={() => setShowAddModal(true)}
            className="ds-button bg-neutral-900 text-white hover:bg-neutral-800 h-10 px-4 min-w-[44px]"
          >
            <Icons.Sync />
            <span className="hidden sm:inline">Add Entry</span>
          </button>
        </div>

        {/* Responsive Table Logic */}
        <div className="ghost-scroll">
          {/* Desktop Table View: Above 1024px */}
          <table className="hidden lg:table w-full text-left border-collapse min-w-[800px]">
            <thead>
              <tr className="bg-[var(--bg-input)]">
                <th className="ds-table-header">Parent Info</th>
                <th className="ds-table-header">Subject Focus</th>
                <th className="ds-table-header">Registry Date</th>
                <th className="ds-table-header">Status</th>
                <th className="ds-table-header text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--border-ds)]">
              {manualMatches.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-8 py-24 text-center text-[var(--text-muted)] italic text-sm">No registry entries detected.</td>
                </tr>
              ) : (
                manualMatches.map((m) => (
                  <tr key={m.id} className="hover:bg-[var(--bg-hover)] transition-colors group">
                    <td className="ds-table-cell">
                      <p className="text-[13px] font-bold text-[var(--text-main)]">{m.parentName}</p>
                      <p className="text-[11px] text-[var(--text-muted)] mt-0.5">{m.phoneNumber}</p>
                    </td>
                    <td className="ds-table-cell">
                      <p className="text-[13px] font-semibold text-[var(--text-main)]">{m.subject}</p>
                      <p className="text-[10px] text-[var(--text-muted)] font-bold uppercase tracking-widest mt-0.5">{m.gradeLevel}</p>
                    </td>
                    <td className="ds-table-cell text-[13px] font-medium text-[var(--text-sub)]">
                      {m.dateAdded}
                    </td>
                    <td className="ds-table-cell">
                      <span className={`px-3 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wider ${getStatusStyles(m.status)}`}>
                        {m.status}
                      </span>
                    </td>
                    <td className="ds-table-cell text-right">
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => setEditingMatch(m)}
                          className="min-h-[44px] min-w-[44px] text-[10px] font-bold text-blue-600 px-3 py-1.5 bg-blue-500/10 rounded-lg hover:bg-blue-500/20 transition-all border border-blue-500/20"
                        >
                          Modify
                        </button>
                        <button
                          onClick={() => handleDelete(m.id, m.parentName)}
                          className="min-h-[44px] min-w-[44px] text-[10px] font-bold text-rose-600 px-3 py-1.5 bg-rose-500/10 rounded-lg hover:bg-rose-500/20 transition-all border border-rose-500/20"
                        >
                          Drop
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>

          {/* Mobile View: Stacked Cards Below 1024px */}
          <div className="lg:hidden p-4 space-y-4">
            {manualMatches.length === 0 ? (
              <div className="py-12 text-center text-[var(--text-muted)] italic text-sm">No entries detected</div>
            ) : (
              manualMatches.map((m) => (
                <div key={m.id} className="ds-card flex flex-col bg-[var(--bg-input)] border border-[var(--border-ds)]">
                  <div className="p-5 space-y-4 flex-1">
                    <div className="flex justify-between items-start">
                      <div className="overflow-hidden">
                        <p className="text-sm font-bold text-[var(--text-main)] truncate">{m.parentName}</p>
                        <p className="text-[10px] text-[var(--text-muted)] mt-0.5 truncate">{m.phoneNumber}</p>
                      </div>
                      <span className={`px-2 py-1 rounded-lg text-[9px] font-bold uppercase tracking-wider ${getStatusStyles(m.status)}`}>
                        {m.status}
                      </span>
                    </div>

                    <div className="grid grid-cols-2 gap-4 text-[11px] font-medium text-[var(--text-sub)]">
                      <div>
                        <p className="text-[9px] font-bold text-[var(--text-muted)] uppercase tracking-widest mb-1">Subject Focus</p>
                        <p className="text-[var(--text-main)] truncate">{m.subject}</p>
                        <p className="text-[9px] uppercase tracking-wider mt-0.5">{m.gradeLevel}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-[9px] font-bold text-[var(--text-muted)] uppercase tracking-widest mb-1">Registry Date</p>
                        <p className="text-[var(--text-main)]">{m.dateAdded}</p>
                      </div>
                    </div>
                  </div>

                  {/* Actions Button Group at Bottom */}
                  <div className="border-t border-[var(--border-ds)] flex divide-x divide-[var(--border-ds)]">
                    <button
                      onClick={() => setEditingMatch(m)}
                      className="flex-1 min-h-[56px] text-[10px] font-bold text-blue-600 hover:bg-blue-500/5 transition-colors uppercase tracking-widest"
                    >
                      Modify
                    </button>
                    <button
                      onClick={() => handleDelete(m.id, m.parentName)}
                      className="flex-1 min-h-[56px] text-[10px] font-bold text-rose-600 hover:bg-rose-500/5 transition-colors uppercase tracking-widest"
                    >
                      Drop
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="ds-modal-overlay">
          <div className="ds-modal-content mx-4">
            <div className="px-6 lg:px-8 py-5 lg:py-6 border-b border-[var(--border-ds)] flex justify-between items-center bg-[var(--bg-card)]">
              <div>
                <h2 className="text-lg font-bold text-[var(--text-main)] tracking-tight">Create Entry</h2>
                <p className="text-[10px] text-[var(--text-sub)] mt-1 uppercase tracking-widest font-bold">New Registry Member</p>
              </div>
              <button onClick={() => setShowAddModal(false)} className="text-[var(--text-muted)] min-h-[44px] min-w-[44px] flex items-center justify-center">
                <Icons.ArrowRight />
              </button>
            </div>
            <div className="ds-modal-body space-y-6 p-6 lg:p-8">
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Parent Identity</label>
                <input
                  type="text"
                  placeholder="e.g. Rahul Sharma"
                  className="ds-input"
                  onChange={(e) => setFormData({ ...formData, parentName: e.target.value })}
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Secure Contact</label>
                <input
                  type="text"
                  placeholder="+91 XXXXX XXXXX"
                  className="ds-input"
                  onChange={(e) => setFormData({ ...formData, phoneNumber: e.target.value })}
                />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Academic Subject</label>
                  <input
                    type="text"
                    placeholder="e.g. Physics"
                    className="ds-input"
                    onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Academic Grade</label>
                  <input
                    type="text"
                    placeholder="e.g. Grade 12"
                    className="ds-input"
                    onChange={(e) => setFormData({ ...formData, gradeLevel: e.target.value })}
                  />
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Initial Status</label>
                <select
                  className="ds-input appearance-none"
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value as Status })}
                >
                  <option value={Status.TRIAL_PENDING}>Trial Pending</option>
                  <option value={Status.ASSIGNED}>Assigned</option>
                  <option value={Status.DROPPED}>Dropped</option>
                </select>
              </div>
            </div>
            <div className="px-6 lg:px-8 py-6 border-t border-[var(--border-ds)] bg-[var(--bg-input)]">
              <button onClick={handleAddSubmit} className="ds-button bg-neutral-900 text-white w-full h-12">
                Record Entry
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Modal */}
      {editingMatch && (
        <div className="ds-modal-overlay">
          <div className="ds-modal-content mx-4">
            <div className="px-6 lg:px-8 py-5 lg:py-6 border-b border-[var(--border-ds)] flex justify-between items-center bg-[var(--bg-card)]">
              <div>
                <h2 className="text-lg font-bold text-[var(--text-main)] tracking-tight">Modify Record</h2>
                <p className="text-[10px] text-[var(--text-sub)] mt-1 uppercase tracking-widest font-bold">State Update</p>
              </div>
              <button onClick={() => setEditingMatch(null)} className="text-[var(--text-muted)] min-h-[44px] min-w-[44px] flex items-center justify-center">
                <Icons.ArrowRight />
              </button>
            </div>
            <div className="ds-modal-body space-y-6 p-6 lg:p-8">
              <div className="p-4 bg-[var(--bg-input)] rounded-xl border border-[var(--border-ds)] overflow-hidden">
                <p className="text-[13px] font-bold text-[var(--text-main)] truncate">{editingMatch.parentName}</p>
                <p className="text-[11px] text-[var(--text-sub)] mt-0.5 truncate">{editingMatch.phoneNumber}</p>
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Update Pipeline Status</label>
                <select
                  className="ds-input appearance-none"
                  value={editingMatch.status}
                  onChange={(e) => setEditingMatch({ ...editingMatch, status: e.target.value as Status })}
                >
                  <option value={Status.TRIAL_PENDING}>Trial Pending</option>
                  <option value={Status.ASSIGNED}>Assigned</option>
                  <option value={Status.DROPPED}>Dropped</option>
                </select>
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Subject Focus</label>
                <input
                  type="text"
                  className="ds-input"
                  value={editingMatch.subject}
                  onChange={(e) => setEditingMatch({ ...editingMatch, subject: e.target.value })}
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-widest ml-1">Grade Level</label>
                <input
                  type="text"
                  className="ds-input"
                  value={editingMatch.gradeLevel}
                  onChange={(e) => setEditingMatch({ ...editingMatch, gradeLevel: e.target.value })}
                />
              </div>
            </div>
            <div className="px-6 lg:px-8 py-6 border-t border-[var(--border-ds)] bg-[var(--bg-input)]">
              <button onClick={handleEditSubmit} className="ds-button bg-neutral-900 text-white w-full h-12 transition-all">
                Save Changes
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ManualMatching;
